server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mini_crm_db
    username: root
    password: your_mysql_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true